name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Specify the Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build
      run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'  # Deploy only on the main branch

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy
      env:
        API_KEY: ${{ secrets.API_KEY }}  # Use secrets for sensitive information
      run: |
        echo "Deploying application..."
        # Add your deployment commands here
