name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

              
    - name: webfactory/ssh-agent  
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIV}}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no root@194.164.61.105 '
        cd /var/www/html/GTS &&
        git pull origin main
